### ISSUE TITLE
Refuse to operate on directories

### ISSUE THREAD

**Issue by ChanceNCounter** [bakfile/bak-python#25]
`bak` is only designed to work on files. It might someday get an option to work on directories, or perhaps a recursive "bak 'em all" method, because recursive dir copies aren't unheard of. In the meantime, however, `bak` should catch `IsADirectoryError`, and output an error instead of crashing.

**Comment by Serene-Arc** [comment]
Would you consider using `pathlib` for this project? I was going to write a pull request for this bug but using `pathlib` would make it a lot cleaner and easier to read. For a lot of stuff, `pathlib` is way better than `os`

**Comment by ChanceNCounter** [comment]
@Serene-Arc probably a good idea, yeah.

**Comment by Serene-Arc** [comment]
Do you want me to do that in a pull request?

**Comment by ChanceNCounter** [comment]
You're absolutely welcome to, or I'll look into it later today or tomorrow. Entirely up to you.
