### ISSUE TITLE
[Errno 18] Invalid cross-device link when doing `bak down`

### ISSUE THREAD

**Issue by dhasial** [bakfile/bak-python#56]
So whenever I do ```bak up```, it works, but I also get `An error occurred.` after the bakfile is made.

And then when I try to do `bak down` to restore the test file, I get:
```
Overwrite /home/user/src/bak/TEST? [y/N]: y
Confirm: Restore /home/user/src/bak/TEST to /home/user/src/bak/TEST and erase bakfiles? [y/N]: y
Traceback (most recent call last):
  File "/usr/local/bin/bak", line 33, in <module>
    sys.exit(load_entry_point('bak==0.0.2a1', 'console_scripts', 'bak')())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/bak-0.0.2a1-py3.9.egg/bak/__main__.py", line 102, in bak_down
  File "/usr/local/lib/python3.9/dist-packages/bak-0.0.2a1-py3.9.egg/bak/commands/__init__.py", line 274, in bak_down_cmd
  File "/usr/lib/python3.9/pathlib.py", line 1377, in rename
    self._accessor.rename(self, target)
OSError: [Errno 18] Invalid cross-device link: '/root/.local/share/bak/bakfiles/home-user-src-bak-TEST.1613262086-135462.bak' -> '/home/user/src/bak/TEST'
```

I've been messing around with bak reinstalling and such, but this happens after I've fully uninstalled any past installation and deleted, I believe, all the leftover files. It's possible this might be a permissions problem, but I recently recursively chowned and chmodded my homedir to 751 so that's probably not it. Also, it seemed to work pretty flawlessly on the very first install, no errors with `bak up`, `bak down` or anything else.

**Comment by ChanceNCounter** [comment]
Fascinating. `shutil` shouldn't do this.

**Comment by ChanceNCounter** [comment]
I'm also slightly concerned that the bakfile directory is in root's home folder.

**Comment by ChanceNCounter** [comment]
Right. Having slept, a couple clarifying questions:

* Is your home directory on another partition? (Mine is, shouldn't matter, but the linking error is a linking error)
* Did you `sudo` install bak, or have you run it as sudo?
* Do you have *both* `/root/.local/share/bak` and `/home/user/.local/share/bak` going? Unless you set $XDG_DATA_HOME to the former, you should only have the latter.

**Comment by ChanceNCounter** [comment]
I'm unable to repro, but I suspect the PR above this comment will fix it.

**Comment by dhasial** [comment]
**1)** Yes, my home directory is on another partition than root.

**2)** Yes, I did `sudo python3 setup.py install --force` because there were permission errors when trying to install without `sudo`:

```
python3 setup.py install --force
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.9/dist-packages/test-easy-install-1074937.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.9/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.
```

Also, at one point I did `sudo pip3 uninstall`, which worked, because doing the normal `pip3 uninstall` gave me the following error message:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/shutil.py", line 806, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.9/dist-packages/bak-0.0.2a1-py3.9.egg' -> '/tmp/pip-uninstall-_s2ieye4/bak-0.0.2a1-py3.9.egg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/home/USER/.local/lib/python3.9/site-packages/pip/_internal/commands/uninstall.py", line 87, in run
    uninstall_pathset = req.uninstall(
  File "/home/USER/.local/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 658, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/home/USER/.local/lib/python3.9/site-packages/pip/_internal/req/req_uninstall.py", line 400, in remove
    moved.stash(path)
  File "/home/USER/.local/lib/python3.9/site-packages/pip/_internal/req/req_uninstall.py", line 289, in stash
    renames(path, new_path)
  File "/home/USER/.local/lib/python3.9/site-packages/pip/_internal/utils/misc.py", line 347, in renames
    shutil.move(old, new)
  File "/usr/lib/python3.9/shutil.py", line 821, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.9/dist-packages/bak-0.0.2a1-py3.9.egg'
```

**3)** When I first installed `bak`, I set `$XDG_DATA_HOME` to `/home/user/.local/share` and haven't changed it since then but probably using `sudo` to install forced `bak` to use the `/root/.local/share/bak` instead.

My memory is crap so I wrote out this whole thing before looking closer at my logs to see I ended up needing to install it with `sudo` because of the permissions, and ended up rewriting this. Hopefully it's better information, and sorry for any clutter / confusion.

**Comment by ChanceNCounter** [comment]
That latest commit is `master` now, it needed merging regardless.

The time you tried `sudo bak up` might be responsible for root's bak dir. I'll have to check if `bak up` does firstrun stuff (should spin that off into a function of its own.)

This also raises the issue of `sudo bak down`.

**Comment by dhasial** [comment]
I rewrote my comment, forgot I _did_ install with `sudo`.

I should mention that it would be nice to be able to run the command both as `sudo` and as a nonprivileged user and I'm not sure if there's any way to do that right now.

**Comment by ChanceNCounter** [comment]
Indeed. That'll require some thought to achieve.

**Comment by ChanceNCounter** [comment]
I don't know if I mentioned it, but I went with falling back on `sudo cp` after a PermissionError. That might evolve in the future.

Also dunno why this issue wasn't closed automatically when that branch was merged, it usually works.
