### ISSUE TITLE
`bak down` prints `NOT KEEP_BAKFILE: []`

### ISSUE THREAD

**Issue by veracioux** [bakfile/bak-python#86]
When I run `bak down file -k 1`, the following message is printed to stdout:
```
Confirm: Restore /tmp/tuterm/home1/todo.txt from bakfile #1 and  bakfiles ? [y/N]: y
NOT KEEP_BAKFILE: []
```

I'm assuming this is a python debug message or something. It would be nicer if the message said `<N> bakfiles discarded` or similar.

**Comment by ChanceNCounter** [comment]
yeap, that was a debug print that got lazily thrown beneath a breakpoint and left behind, thanks for the report

**Comment by ChanceNCounter** [comment]
Apparently, I already hit this in an unmerged cleanup branch. I'll merge it now. Count to 100 and pull unstable.
